<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-PB.Proposta-a431d37c-3596-4c5a-97d0-efddbb23bac8</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="PB.Proposta.Application\**" />
    <Compile Remove="PB.Proposta.Domain\**" />
    <Compile Remove="PB.Proposta.Infrastructure\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="PB.Proposta.Application\PB.Proposta.Application.csproj" />
    <ProjectReference Include="PB.Proposta.Infrastructure\PB.Proposta.Infrastructure.csproj" />
  </ItemGroup>

</Project>